# Generated by Django 2.0.9 on 2018-11-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.BooleanField()),
                ('player1', models.TextField()),
                ('player2', models.TextField()),
            ],
        ),
    ]
