# Generated by Django 2.0.9 on 2018-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_field_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='game_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=0)),
                ('room_url', models.CharField(default='room_url', max_length=5)),
                ('player1_name', models.CharField(default='player1', max_length=20)),
                ('player2_name', models.CharField(default='player2', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='game_field',
        ),
    ]
