# Generated by Django 2.0.9 on 2018-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181124_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='player1',
            field=models.CharField(default='player1_id', max_length=20),
        ),
        migrations.AddField(
            model_name='game_data',
            name='player2',
            field=models.CharField(default='player2_id', max_length=20),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='player1_name',
            field=models.CharField(default='player1_name', max_length=20),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='player2_name',
            field=models.CharField(default='player2_name', max_length=20),
        ),
    ]
