# Generated by Django 2.0.9 on 2018-11-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181124_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_data',
            old_name='player1',
            new_name='player1_id',
        ),
        migrations.RenameField(
            model_name='game_data',
            old_name='player2',
            new_name='player2_id',
        ),
    ]
