# Generated by Django 2.0.9 on 2018-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181125_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='board',
            field=models.CharField(default='000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='game_data',
            name='room_url',
            field=models.CharField(default='url', max_length=5),
        ),
    ]
