# Generated by Django 2.0.9 on 2018-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181125_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='room_url',
            field=models.CharField(default='url', max_length=11),
        ),
    ]
