# Generated by Django 2.0.9 on 2018-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20181125_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_data',
            name='board',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
